### ISSUE TITLE
Aufgabe4

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#1]
Aufgabe 4 zum Review bereit.
dir: /aufgabe1/src

**Comment by wy-bbw** [comment]
In der Aufgabenstellung steht noch, dass die Abgabe in ein Unterverzeichnis UML soll. ("Die Lösungen werden in dem Github Repository unter dem Verzeichnis UML abgelegt und im Wiki verlinkt."). Es wäre gut, dass dahin zu verschieben.

**Comment by derfelix54** [comment]
Du meinst den Ordner src zu UML umbenennen?

**Comment by S-Canoski** [comment]
Code wurde einer Review unterzogen:
-Fehlende Java-Doc Kommentare wurden dem Code hinzugefügt.
-Umsetzung des UML-Diagramms in Java-Code hat gepasst.
