### ISSUE TITLE
Blatt 2 - Aufgabe 7

### ISSUE THREAD

**Issue by S-Canoski** [sweIhm-ws2018-19/skillproject-do-4#10]
Aufgabe 7 zur review freigegeben.

**Comment by derfelix54** [comment]
Passt meiner Meinung nach. Du hast Sichtbarkeit bei allen auf public gesetzt. Streng genommen kann man das dem Diagramm nicht entnehmen.

**Comment by wy-bbw** [comment]
"In Seqeuenzdiagrammen werden Methodenaufrufe eingetragen. Jeder Methodenaufruf
wird als eine gerichtete Kante (mit gefüllter Pfeilspitze) vom Aufrufer zum Aufgerufenen
gezeichnet" ["Böttcher, UML Jitt-Text, 1. Semester]. Dementsprechend ist die Methode tu_was() der Klasse A zuzuordnen, die Methode start() der Klasse B etc. Die Zuordnung ist hier falsch vorgenommen worden. Dass eine Methode auf einer anderen Klasse aufgerufen wird, impliziert imho eine Assoziation. Das soll auch gekennzeichnet werden.

**Comment by S-Canoski** [comment]
Zuordnung der Methoden zu den einzelnen Klassen wurde geändert.
Implikation der Assoziationen nicht vollends verstanden, bitte reviewen und gegebenenfalls anpassen.
