### ISSUE TITLE
Review von Fallbeschreibung

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#15]
Könntet ihr schauen ob das so in der Richtung passt? Hab eine Tabelle hochgeladen

**Comment by wy-bbw** [comment]
Inhaltlich sehr gut. Es wäre aber nicht schlecht, es noch in die Form zu bringen, die in der Vorlesung besprochen wurde. Also eine Tabelle in der Art
![anwendungsfallbeschreibung](https://user-images.githubusercontent.com/22498487/48510964-9c7b7180-e855-11e8-897d-232bcbd3cd36.png)

**Comment by S-Canoski** [comment]
Anpassungen zu einer Tabelle wie in der Vorlesung wurde vorgenommen.
