### ISSUE TITLE
version 1 von handler reviewn

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#23]

**Comment by S-Canoski** [comment]
Review einzelner Klassen:

- [x] AlibiIntentHandler: Syntaktisch und Semantisch korrekt, Alexa Aussage ist vorhanden und wird korrekt wiedergegeben.

- [x] CancelandStopIntenthandler: In einzelne Klassen aufgeteilt werden, um klar zwischen stoppen (am ende eines Alibis) und abbrechen (während der generierung) zu unterscheiden.

- [x] FallbackIntentHandler: Syntaktisch und Semantisch korrekt, Alexa Aussage ist vorhanden und wird korrekt wiedergegeben.

- [x] HelpIntentHandler: Vorgabe, dass Alexa Antowrt noch nicht eine konkrete Datumsformat und Zeitformat abfragt wurde eingehalten.

- [x] LaunchRequestHandler: Syntaktisch und Semantisch korrekt, Alexa Aussage ist vorhanden und wird korrekt wiedergegeben.

- [x] SessionEndedRequestHandler: Syntaktisch und Semantisch korrekt, Alexa Aussage ist vorhanden und wird korrekt wiedergegeben.

- [x] AlibiStreamHandler: Syntaktisch und Semantisch korrekt, Alexa Aussage ist vorhanden und wird korrekt wiedergegeben.

**Comment by derfelix54** [comment]
abgeschlossen
