### ISSUE TITLE
Änderungen Produktivcode

### ISSUE THREAD

**Issue by wy-bbw** [sweIhm-ws2018-19/skillproject-do-4#24]
- das Ding baut nicht ...
- variadischer Ctor funktioniert nicht. (Attribute werden nicht mit defaults initialisiert)
- toString von Alibi: JSON-Format waere gut
- alibiprovider könnte Interface sein (hat zumindest keine Methoden).
- csvprovider akzeptiert keine Kommaseparierten Files.
- Absicherung bitte verbessern.

**Comment by adrianhollow** [comment]
vararg removed
toString of Alibi is CSV compatible#
CSVProvider is compatible with Alibi::toString()
AlibiProvider is an interface now
no exceptions are actively thrown
