### ISSUE TITLE
Amazon Account for Skill Testing

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#25]
Bitte alle einen Amazon Account erstellen.
-Timmy und Wolfgang fehlen noch-
und mir schicken.

Muss die Accounts zum Testen eintragen

**Comment by wy-bbw** [comment]
kallies@hm.edu

**Comment by S-Canoski** [comment]
canoski@hm.edu

**Comment by adrianhollow** [comment]
tphan@hm.edu
