### ISSUE TITLE
Blatt 2 A1

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#4]
Ready to Review

**Comment by wy-bbw** [comment]
Edit:
Videoaufnahme sollte passen. "Text" muss gelöscht werden. Bei Blitz einstellen müssen die Pfeile von on, off und auto imho in die umgekehrte Richtung zeigen (sind keine include-Fälle, sondern Realisierungen imho)

**Comment by wy-bbw** [comment]
PS: bitte keine Umlaute in Filenamen.

**Comment by derfelix54** [comment]
file wurde aktualisiert und nochmals hochgeladen.
