### ISSUE TITLE
sonarqube issues

### ISSUE THREAD

**Issue by wy-bbw** [sweIhm-ws2018-19/skillproject-do-4#40]
Unser Code geht nicht durch das Quality Gate von Sonarqube (S. Sonarqube Info)

Bitte die von Sonarqube monierten Issues beheben. Sobald das der Fall ist, muss ich die Tests anpassen.

**Comment by derfelix54** [comment]
wo sieht man denn diese Sonarqube issues

**Comment by wy-bbw** [comment]
Sonarqube ist in moodle unter continuous integration (oder so) verlinkt, von dort einfach zu unserem Projekt durchklicken
