### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#41]
[ERROR] Failures: 
[ERROR]   AlibiFilterTest.setup:20 file alibisource.csv should exist, but does not ==> expected: <true> but was: <false>
[ERROR]   AlibiGeneratorTest.setup:25 alibisource.csv should exist, but does not ==> expected: <true> but was: <false>
[ERROR]   CsvProviderTest.testProvideAlibi:65 File "alibisource.csv"should exist, but doesnt ==> expected: <true> but was: <false>

Kann ich irgendwas tun um das zu beheben?
Oder macht das Wolfgang noch ?

Einen Guten Rutsch an Alle!

**Comment by wy-bbw** [comment]
Scheint kein Problem zu sein, zumindest nicht fuer Travis
