### ISSUE TITLE
Blatt 2 A3

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#5]
ready to review

**Comment by wy-bbw** [comment]
Pfeilarten (durchgezogen/Annotationen/Köpfe) im Diagramm stimmen nicht mit dem Beispiel im Aufgabenblatt überein. System könnte noch benannt werden,

**Comment by derfelix54** [comment]
würde system nicht benennen. Pfeile stimmen jetzt überein
