### ISSUE TITLE
Blatt 2 Aufgabe 4

### ISSUE THREAD

**Issue by derfelix54** [sweIhm-ws2018-19/skillproject-do-4#6]
ready to review

**Comment by wy-bbw** [comment]
Beschriftungen der Pfade nach dem Entscheidungsknoten sind glaube ich nicht optional (aka genug Licht/ nicht ausreichend Licht). Ich würde die Beleuchtung vor dem Öffnen der Blende messen, aber da kenn ich mich nicht gut genug aus und würde das in dem Fall an den Rest der Gruppe weiterleiten.

**Comment by derfelix54** [comment]
Naja die Belichtung kann ja nicht gemessen werden wenn die Blende geschlossen ist. Die Belichtungszeit hängt ja von der Blende ab. Macht also keinen Sinn die Blende beim messen nicht offen zu haben.

**Comment by wy-bbw** [comment]
Bin kein Kameraexperte. Würde aber vermuten, dass man einen Sensor auch außerhalb der Blende anbringen kann, der dann die Umgebungshelligkeit analysiert (geht auch bei geschlossener Blende). Egal, dann lassen wir es so.

**Comment by wy-bbw** [comment]
An der Verzweigung fehlen noch die Beschreibungen der Bedingung.

**Comment by derfelix54** [comment]
hab es nochmal hochgeladen

**Comment by wy-bbw** [comment]
Passt
