### ISSUE TITLE
Blatt 2 Aufgabe 9

### ISSUE THREAD

**Issue by adrianhollow** [sweIhm-ws2018-19/skillproject-do-4#9]
free to review

**Comment by S-Canoski** [comment]
Bei folgendem Sequenzdiagramm sollten die Datentypen der Methodenaufrufe ergänzt werden.
Unter dem Rollensymbol "text2: Text" befindet sich auf der Lebenslinie die Beschreibung "Text", jedoch ist nicht ersichtlich wieso.

**Comment by adrianhollow** [comment]
issue fixed
